name: kalorientracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0  # Choose a version that supports Dart SDK 2.12.0
  http: ^0.13.3  # Choose a version that supports Dart SDK 2.12.0
  
  json_annotation: ^4.8.1
  pdf: ^3.10.7

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
